template_type = 0

[map]
creator = "x3nx1"
title = "N01Z Demo"
description = "This is the default demo map."
date_updated = "07/09/2026"
is_alpha_release = false
##
[map.constants]
audio_track = "%default%"
##
[map.itemdata]
#
[[map.itemdata.mitem]]
item_name = "noscope"
item_location = [300.0, 100.0]


##
[map.data]
#
[[map.data.mdata]]
type = 4
mode = 0
verts = [[0.0, 0.0], [200.0, 0.0], [200.0, 300.0], [0.0, 250.0]]
[[map.data.mdata]]
type = 4
mode = 0
verts = [[200.0, 0.0], [800.0, 0.0], [800.0, 250.0], [200.0, 250.0]]
[[map.data.mdata]]
type = 4
mode = 1
verts = [[195.0, 75.0], [215.0, 75.0], [195.0, 175.0], [215.0, 175.0]]
[[map.data.mdata]]
type = 4
mode = 1
verts = [[400.0, 110.0], [400.0, 140.0], [650.0, 110.0], [650.0, 140.0]]
### END ###